CREATE OR REPLACE FUNCTION hkey( text ) RETURNS text
AS
  'hkey.so', 'hkey'
LANGUAGE C STRICT IMMUTABLE;

REVOKE ALL ON FUNCTION hkey( TEXT ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION hkey( TEXT ) TO admins;